global:
  scrape_interval: 15s # Set the interval to collect metrics every 15 seconds

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['pa_backend1:8000', 'pa_backend2:8000'] 