global:
  scrape_interval: 15s # Set the interval to collect metrics every 15 seconds

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000'] # Target the backend service container on port 8000