# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x08searchpb\"C\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x14\n\x0cworkspace_id\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"[\n\x0cSearchResult\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x03\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0cstorage_path\x18\x03 \x01(\t\x12\x12\n\nsimilarity\x18\x04 \x01(\x02\"9\n\x0eSearchResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.searchpb.SearchResult2L\n\rSearchService\x12;\n\x06Search\x12\x17.searchpb.SearchRequest\x1a\x18.searchpb.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=26
  _globals['_SEARCHREQUEST']._serialized_end=93
  _globals['_SEARCHRESULT']._serialized_start=95
  _globals['_SEARCHRESULT']._serialized_end=186
  _globals['_SEARCHRESPONSE']._serialized_start=188
  _globals['_SEARCHRESPONSE']._serialized_end=245
  _globals['_SEARCHSERVICE']._serialized_start=247
  _globals['_SEARCHSERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
