# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\tstoragepb\"\'\n\x0f\x44ownloadRequest\x12\x14\n\x0cstorage_path\x18\x01 \x01(\t\"^\n\x10\x44ownloadResponse\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x12\n\nsize_bytes\x18\x04 \x01(\x03\"%\n\rDeleteRequest\x12\x14\n\x0cstorage_path\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9c\x01\n\x0eStorageService\x12G\n\x0c\x44ownloadFile\x12\x1a.storagepb.DownloadRequest\x1a\x1b.storagepb.DownloadResponse\x12\x41\n\nDeleteFile\x12\x18.storagepb.DeleteRequest\x1a\x19.storagepb.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOWNLOADREQUEST']._serialized_start=28
  _globals['_DOWNLOADREQUEST']._serialized_end=67
  _globals['_DOWNLOADRESPONSE']._serialized_start=69
  _globals['_DOWNLOADRESPONSE']._serialized_end=163
  _globals['_DELETEREQUEST']._serialized_start=165
  _globals['_DELETEREQUEST']._serialized_end=202
  _globals['_DELETERESPONSE']._serialized_start=204
  _globals['_DELETERESPONSE']._serialized_end=237
  _globals['_STORAGESERVICE']._serialized_start=240
  _globals['_STORAGESERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
